apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mynginx
  namespace: nginx
spec:
  interval: 1m
  path: ./nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
