apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-release
  namespace: flux-conf-ns
spec:
  interval: 1m
  chart:
    spec:
      chart: nginx-chart
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: acr-helm
        namespace: flux-conf-ns
  values:
    # override values.yaml here if needed
    replicaCount: 2
