apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: acr-helm
  namespace: flux-system
spec:
  type: oci
  provider: azure
  interval: 1m
  url: oci://azdevopsreg.azurecr.io/helm
